stages:
  - build
  - test
  - deploy

test_job:
  stage: test
  script:
    - dotnet test

deploy-nuget:
  stage: deploy
  dependencies:
    - test_job
  script:
    - dotnet pack -c Release
    - dotnet nuget remove source gitlab_spooksoft_hexeditor
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab_spooksoft_hexeditor --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "**/release/*.nupkg" --source gitlab_spooksoft_hexeditor
  only:
    - main